from collections.abc import Iterator
from typing import Any

from tlslite import api as api
from tlslite import errors as errors
from tlslite import utils as utils

class TLSConnection:
    def __init__(self, sock: Any) -> None: ...
    def handshakeServerAsync(self, **kwargs: Any) -> Iterator[None]: ...  # noqa: N802
    def recv(self, bufsize: int) -> bytes: ...
    def send(self, data: bytes) -> int: ...
    def close(self) -> None: ...
    def shutdown(self, how: Any) -> None: ...

class HandshakeSettings: ...
class TLSAbruptCloseError(Exception): ...
